CREATE TABLE CLIENT
(
    ID SERIAL PRIMARY KEY,
    USERNAME TEXT NOT NULL,
    RATING INTEGER CHECK (RATING >= 0),
    EMAIL TEXT
);

CREATE TABLE HOME_PAGE
(
    USER_ID INTEGER REFERENCES CLIENT ON DELETE CASCADE PRIMARY KEY,
    ABOUT TEXT
);

CREATE TABLE CONTEST
(
    ID SERIAL PRIMARY KEY,
    DATE DATE NOT NULL,
    DURATION INTEGER NOT NULL CHECK (DURATION >= 0),
    MIN_REQUIRED_RATING INTEGER CHECK (MIN_REQUIRED_RATING >= 0)
);

CREATE TABLE CONTEST_PARTICIPATION
(
    USER_ID INTEGER REFERENCES CLIENT ON DELETE CASCADE,
    CONTEST_ID INTEGER REFERENCES CONTEST ON DELETE CASCADE,
    PLACE INTEGER CHECK (PLACE >= 0),
    PRIMARY KEY (USER_ID, CONTEST_ID)
);

CREATE TABLE COLOR
(
    ID SERIAL PRIMARY KEY,
    NAME TEXT
);

CREATE TABLE PALLETE
(
    ID SERIAL PRIMARY KEY
);

CREATE TABLE PALLETE_COLORS
(
    PALLETE_ID INTEGER REFERENCES PALLETE ON DELETE CASCADE,
    COLOR_ID INTEGER REFERENCES CONTEST ON DELETE CASCADE,
    PRIMARY KEY (PALLETE_ID, COLOR_ID)
);

CREATE TYPE IMAGE_TYPE AS ENUM
(
    'PLAIN_IMAGE',
    'GIF'
);

CREATE TABLE IMAGE_PROPERTIES
(
    ID SERIAL PRIMARY KEY,
    MIN_WIDTH INTEGER CHECK (MIN_WIDTH >= 0),
    MAX_WIDTH INTEGER CHECK (MAX_WIDTH >= 0),
    MIN_HEIGHT INTEGER CHECK (MIN_HEIGHT >= 0),
    MAX_HEIGHT INTEGER CHECK (MAX_HEIGHT >= 0),
    DURATION INTEGER CHECK (DURATION >= 0),
    TYPE IMAGE_TYPE,
    MIN_COLOR_COUNT INTEGER CHECK (MIN_COLOR_COUNT >= 0),
    MAX_COLOR_COUNT INTEGER CHECK (MAX_COLOR_COUNT >= 0),
    PALLETE_ID INTEGER REFERENCES PALLETE ON DELETE SET NULL,
    MAX_FILE_SIZE INTEGER CHECK (MAX_FILE_SIZE >= 0)
);

CREATE TABLE TASK
(
    ID SERIAL PRIMARY KEY,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT,
    IMAGE_PROPS_ID INTEGER REFERENCES IMAGE_PROPERTIES SET NULL
);

CREATE TABLE TASK_TABLE
(
    CONTEST_ID INTEGER REFERENCES CONTEST ON DELETE CASCADE,
    TASK_ID INTEGER REFERENCES TASK ON DELETE CASCADE,
    PRIMARY KEY (CONTEST_ID, TASK_ID)
);

CREATE TABLE IMAGE
(
    ID SERIAL PRIMARY KEY,
    FILENAME TEXT
);

CREATE TABLE PERSONAL_TASK
(
    ID SERIAL PRIMARY KEY,
    TASK_ID INTEGER REFERENCES TASK ON DELETE CASCADE,
    USER_ID INTEGER REFERENCES CLIENT ON DELETE CASCADE,
    SUBMITTED BOOLEAN,
    IMAGE_ID INTEGER REFERENCES IMAGE ON DELETE SET NULL
);

CREATE TABLE VOTING_TABLE
(
    IMAGE_ID INTEGER REFERENCES IMAGE ON DELETE CASCADE,
    VOTING_USER_ID INTEGER REFERENCES CLIENT ON DELETE SET NULL,
    CHOSED BOOLEAN
);